("cb_note_365", "cb note 365"),
("ui_hero_strengthen_string_1", "ui hero strengthen string 1"),
("ui_hero_strengthen_string_2", "ui hero strengthen string 2"),
("ui_hero_strengthen_string_3", "ui hero strengthen string 3"),
("ui_hero_strengthen_string_4", "ui hero strengthen string 4"),
("ui_hero_strengthen_string_5", "ui hero strengthen string 5"),
("ui_hero_strengthen_string_6", "ui hero strengthen string 6"),
("ui_hero_strengthen_string_7", "ui hero strengthen string 7"),
("ui_hero_strengthen_string_8", "ui hero strengthen string 8"),
("ui_hero_strengthen_string_9", "ui hero strengthen string 9"),
("ui_hero_strengthen_string_10", "ui hero strengthen string 10"),
("ui_hero_strengthen_string_10_1", "ui hero strengthen string 10 1"),
("ui_hero_strengthen_string_11", "ui hero strengthen string 11"),
("ui_hero_strengthen_string_12", "ui hero strengthen string 12"),
("ui_hero_strengthen_string_13", "ui hero strengthen string 13"),
("ui_hero_strengthen_string_14", "ui hero strengthen string 14"),
("ui_hero_strengthen_string_15", "ui hero strengthen string 15"),
("ui_hero_strengthen_string_16", "ui hero strengthen string 16"),
("ui_hero_strengthen_string_17", "ui hero strengthen string 17"),
("ui_hero_strengthen_string_18", "ui hero strengthen string 18"),
("ui_hero_strengthen_string_19", "ui hero strengthen string 19"),
("ui_hero_strengthen_string_20", "ui hero strengthen string 20"),
("ui_hero_strengthen_string_21", "ui hero strengthen string 21"),
("ui_hero_strengthen_string_22", "ui hero strengthen string 22"),
("ui_hero_strengthen_string_23", "ui hero strengthen string 23"),
("ui_hero_strengthen_string_24", "ui hero strengthen string 24"),
("ui_hero_strengthen_string_25", "ui hero strengthen string 25"),
("ui_hero_strengthen_string_26", "ui hero strengthen string 26"),
("ui_hero_strengthen_string_27", "ui hero strengthen string 27"),
("ui_hero_strengthen_string_28", "ui hero strengthen string 28"),
("ui_hero_strengthen_string_29", "ui hero strengthen string 29"),
("ui_hero_strengthen_string_30", "ui hero strengthen string 30"),
("ui_hero_strengthen_string_31", "ui hero strengthen string 31"),
("ui_hero_strengthen_string_32", "ui hero strengthen string 32"),
("ui_hero_strengthen_string_33", "ui hero strengthen string 33"),
("ui_hero_strengthen_string_34", "ui hero strengthen string 34"),
("ui_hero_strengthen_string_35", "ui hero strengthen string 35"),
("ui_hero_strengthen_string_36", "ui hero strengthen string 36"),
("ui_hero_strengthen_string_37", "ui hero strengthen string 37"),
("ui_hero_strengthen_string_38", "ui hero strengthen string 38"),
("ui_hero_strengthen_string_39", "ui hero strengthen string 39"),
("ui_hero_strengthen_string_40", "ui hero strengthen string 40"),
("ui_hero_strengthen_string_41", "ui hero strengthen string 41"),
("ui_hero_strengthen_string_42", "ui hero strengthen string 42"),
("ui_hero_strengthen_string_43", "ui hero strengthen string 43"),
("ui_hero_strengthen_string_44", "ui hero strengthen string 44"),
("ui_hero_strengthen_string_45", "ui hero strengthen string 45"),
("ui_hero_strengthen_string_46", "ui hero strengthen string 46"),
("ui_hero_strengthen_string_47", "ui hero strengthen string 47"),
("ui_hero_strengthen_string_48", "ui hero strengthen string 48"),
("ui_hero_strengthen_string_49", "ui hero strengthen string 49"),
("ui_hero_strengthen_string_50", "ui hero strengthen string 50"),
("ui_hero_strengthen_string_51", "ui hero strengthen string 51"),
("ui_hero_strengthen_string_52", "ui hero strengthen string 52"),
("ui_hero_strengthen_string_53", "ui hero strengthen string 53"),
("ui_hero_strengthen_string_54", "ui hero strengthen string 54"),
("ui_hero_strengthen_string_54_1", "ui hero strengthen string 54 1"),
("ui_hero_strengthen_string_55", "ui hero strengthen string 55"),
("ui_hero_strengthen_string_56", "ui hero strengthen string 56"),
("ui_hero_strengthen_string_57", "ui hero strengthen string 57"),
("ui_hero_strengthen_string_58", "ui hero strengthen string 58"),
("ui_hero_strengthen_string_59", "ui hero strengthen string 59"),
("ui_hero_strengthen_string_60", "ui hero strengthen string 60"),
("ui_hero_strengthen_string_61", "ui hero strengthen string 61"),
("ui_hero_strengthen_string_62", "ui hero strengthen string 62"),
("ui_hero_strengthen_string_63", "ui hero strengthen string 63"),
("ui_hero_strengthen_string_64", "ui hero strengthen string 64"),
("ui_hero_strengthen_string_65", "ui hero strengthen string 65"),
("ui_hero_strengthen_string_66", "ui hero strengthen string 66"),
("ui_hero_strengthen_string_67", "ui hero strengthen string 67"),
("ui_hero_strengthen_string_68", "ui hero strengthen string 68"),
("ui_hero_strengthen_string_69", "ui hero strengthen string 69"),
("ui_hero_strengthen_string_70", "ui hero strengthen string 70"),
("ui_hero_strengthen_string_71", "ui hero strengthen string 71"),
("ui_hero_strengthen_string_72", "ui hero strengthen string 72"),
("ui_hero_strengthen_string_73", "ui hero strengthen string 73"),
("ui_hero_strengthen_string_74", "ui hero strengthen string 74"),
("ui_hero_strengthen_string_75", "ui hero strengthen string 75"),
("ui_hero_strengthen_string_76", "ui hero strengthen string 76"),
("ui_hero_strengthen_string_77", "ui hero strengthen string 77"),
("ui_hero_strengthen_string_78", "ui hero strengthen string 78"),
("ui_hero_strengthen_string_79", "ui hero strengthen string 79"),
("ui_hero_strengthen_string_82", "ui hero strengthen string 82"),
("ui_hero_strengthen_string_83", "ui hero strengthen string 83"),
("ui_hero_strengthen_string_84", "ui hero strengthen string 84"),
("auto_point_return_to_map", "anto point return to map"),
("auto_point_reset", "anto point reset"),
("auto_point_reset_stats", "anto point reset stats"),
("is_open_auto_add_point", "is open auto add point"),
("auto_point_select_scheme", "anto point select scheme"),
("auto_point_add_scheme", "anto point add scheme"),
("auto_point_force_add", " "),
("auto_point_no", "{reg10}"),
("auto_point_input_default", "anto point input default"),
("auto_point_combox_default", "anto point combox default"),
("auto_point_input_default_infantry", "auto point input default infantry"),
("auto_point_input_default_cavalry", "auto point input default cavalry"),
("auto_point_input_default_archers", "auto point input default archers"),
("auto_point_input_default_horse_archers", "auto point input default horse archers"),
("auto_point_input_default_crossbow", "auto point input default crossbow"),
("auto_point_input_default_none", "auto point input default none"),
("auto_point_not_money", "auto point not money"),
("auto_point_not_free_cap", "auto point not free cap"),
("auto_you_want_to_reset_stats", "auto you want to reset stats"),
("auto_point_not_move_item", "auto point not move item"),
("auto_you_want_to_select_scheme", "auto you want to select scheme"),
("auto_you_want_to_add_scheme", "auto you want to add scheme"),
("auto_companion_select_intro", "auto companion select intro"),
("auto_global_switch_intro", "auto global switch intro"),
("auto_scheme_select_intro", "auto scheme select intro"),
("auto_scheme_name_intro", "auto scheme name intro"),
("auto_scheme_apply_intro", "auto scheme apply intro"),
("auto_scheme_save_intro", "auto scheme save intro"),
("auto_skill_select_intro", "auto skill select intro"),
("auto_skill_target_intro", "auto skill target intro"),
("auto_skill_force_intro", "auto skill force intro"),
("auto_exp_info_intro", "auto exp info intro"),
("auto_hp_info_intro", "auto hp info intro"),
("auto_respec_cost_intro", "auto respec cost intro"),
("auto_rebuild_confirm_intro", "auto rebuild confirm intro"),
("auto_ui_close_intro", "auto ui close intro"),
("auto_s1_plus", "{s1}+"),
("auto_star_s1", "*{s1}"),
("auto_reg1", "{reg1}"),
("auto_reg50_reg51", "({reg50},{reg51})"),
("auto_reg10", "{reg10}"),
("auto_reg0", "{reg0}"),
("auto_reg11_reg10_reg12", "{!}{reg11}({reg10}+{reg12})"),
("auto_reg10_simple", "{!}{reg10}"),
("auto_s1_s2", "{s1}^^{s2}"),
("auto_plus", "+"),
("auto_extra_tip_consum", "auto extra tip consum"),